### ISSUE TITLE
User rejected 

### ISSUE THREAD

**Issue by ganeshthandapani** [aman00323/email-checker#18]
Hi Aman thanks for the solution, while using this email checker process to verify Hotmail, outlook I face some problems. Can you asses me. I get a message as the <b>User rejected</b> after verifying some 20 to 30 emails with the same Hotmail and outlook emails. Any idea of it.

**Comment by aman00323** [comment]
@ganeshthandapani May be its due to rapid request from your server to hotmail with same ip address.

Most of morden server firewall and technics  use this kind of method, if you do rapid request then it should block your ip address. 

This kind of practice follow to prevent (Brute Force) attack on server.

I would suggest that you may follow some interval to check between emails.

**Comment by ganeshthandapani** [comment]
Thanks for the reply, Aman. What's the time interval should be maintained to avoid such cases. Any Idea

**Comment by aman00323** [comment]
@ganeshthandapani You can interval of 5 sec and try it out.

**Comment by aman00323** [comment]
@ganeshthandapani Should i close this ?
